default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: to_do_manager_development
  username: <%= ENV["TO_DO_MANAGER_DEV_DATABASE_USERNAME"] %>
  password: <%= ENV["TO_DO_MANAGER_DEV_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: to_do_manager_test
  username: <%= ENV["TO_DO_MANAGER_DEV_DATABASE_USERNAME"] %>
  password: <%= ENV["TO_DO_MANAGER_DEV_DATABASE_PASSWORD"] %>

production:
  primary: &primary_production
    <<: *default
    database: to_do_manager_production
    username: to_do_manager
    password: <%= ENV["TO_DO_MANAGER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: to_do_manager_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: to_do_manager_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: to_do_manager_production_cable
    migrations_paths: db/cable_migrate
